Toys/JavaSource/tr/com/arf/framework/view/controller/form/_base/BaseFilteredController.java
package tr.com.arf.framework.view.controller.form._base;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

import javax.faces.model.SelectItem;

import tr.com.arf.framework.db._management.DBOperator;
import tr.com.arf.framework.db.filter._base.BaseFilter;
import tr.com.arf.framework.db.model._base.BaseEntity;
import tr.com.arf.framework.db.model.query.QueryObject;
import tr.com.arf.framework.utility.tool.KeyUtil;
import tr.com.arf.framework.utility.tool.CodeGeneratorStringUtil;

@SuppressWarnings("serial")
public abstract class BaseFilteredController extends BaseController {

	Calendar today = Calendar.getInstance();

	private String masterObjectName;
	private String masterOutcome;

	protected BaseFilteredController(@SuppressWarnings("rawtypes") Class c) {
		super(c);
	}

	public String backToMaster() {
		if (getMasterOutcome() != null) {
			return CodeGeneratorStringUtil.makeFirstCharLowerCase(getMasterOutcome()) + ".do";
		} else {
			return "";
		}
	}

	public abstract BaseFilter getFilter();

	public void resetFilter() {
		resetFilterOnly();
		queryAction();
	}

	public void resetFilterOnly() {
		tableRowCancelSelection();
		getFilter().clearQueryCriterias();
		getFilter().init();
		getFilter().createQueryCriterias();
		setTable(null);
	}

	@SuppressWarnings("unchecked")
	@Override
	public void queryAction() {
		DBOperator dbOperator = getDBOperator();
		List<BaseEntity> itemList = new ArrayList<BaseEntity>();
		tableRowCancelSelection();
		ArrayList<ArrayList<QueryObject>> allCriterias = (ArrayList<ArrayList<QueryObject>>) getFilter().createQueryCriterias();
		if (!isEmpty(allCriterias)) {
			if (!isEmpty(allCriterias.get(0))) {
				ArrayList<QueryObject> opsiyonelKriterler = new ArrayList<QueryObject>();
				if (!isEmpty(allCriterias.get(1))) {
					opsiyonelKriterler = allCriterias.get(1);
				}
				setRecordCount(dbOperator.recordCountFiltered(getModelName(), allCriterias.get(0), opsiyonelKriterler).intValue());
				itemList = dbOperator.loadFiltered(getModelName(), allCriterias.get(0), opsiyonelKriterler, getRecordInterval(), getOrderField());
				setListMessage(KeyUtil.getFrameworkLabel("list.toplam") + " " + getRecordCount() + " " + KeyUtil.getFrameworkLabel("kayit.bulundu"));
				setList(itemList);
				return;
			}
		}
		setRecordCount(dbOperator.recordCountAll(getModelName()).intValue());
		itemList = dbOperator.loadAll(getModelName(), getRecordInterval(), getOrderField());
		setListMessage(KeyUtil.getFrameworkLabel("list.toplam") + " " + getRecordCount() + " " + KeyUtil.getFrameworkLabel("kayit.bulundu"));
		setList(itemList);
	}

	@SuppressWarnings("unchecked")
	public SelectItem[] getFilteredSelectItemList() {
		ArrayList<QueryObject> kriterler = getFilter().createQueryCriterias().get(0);
		List<BaseEntity> entityList;
		entityList = getDBOperator().loadFiltered(getModelName(), kriterler, getFilter().createQueryCriterias().get(1), null, getOrderField());
		SelectItem[] selectItemList = new SelectItem[entityList.size() + 1];
		selectItemList[0] = new SelectItem(null, "");
		int i = 1;
		for (BaseEntity entity : entityList) {
			selectItemList[i++] = new SelectItem(entity, entity.getUIString());
		}
		return selectItemList;
	}

	public void newFilter() {
		super.changePage("first");
		setSelection(null);
		setTable(null);
		ArrayList<QueryObject> kriterler = getFilter().createQueryCriterias().get(0);
		if (!isEmpty(kriterler)) {
			getFilter().createQueryCriterias();
			queryAction();
		}
	}

	@Override
	public void browse() {
		queryAction();
		super.cancel();
	}

	public String getMasterOutcome() {
		return masterOutcome;
	}

	public void setMasterOutcome(String masterOutcome) {
		this.masterOutcome = masterOutcome;
	}

	public String getMasterObjectName() {
		return masterObjectName;
	}

	public void setMasterObjectName(String masterObjectName) {
		this.masterObjectName = masterObjectName;
	}
}

Toys/JavaSource/tr/com/arf/framework/view/controller/form/_base/BaseFilteredControllerNoPaging.java
package tr.com.arf.framework.view.controller.form._base;

import java.util.ArrayList;
import java.util.List;

import tr.com.arf.framework.db._management.DBOperator;
import tr.com.arf.framework.db.model._base.BaseEntity;
import tr.com.arf.framework.db.model.query.QueryObject;
import tr.com.arf.framework.utility.tool.KeyUtil;

public abstract class BaseFilteredControllerNoPaging extends BaseFilteredController {

	private static final long serialVersionUID = 6393308819569413390L;

	protected BaseFilteredControllerNoPaging(@SuppressWarnings("rawtypes") Class c) {
		super(c);
	}

	@SuppressWarnings("unchecked")
	@Override
	public void queryAction() {
		DBOperator dbOperator = getDBOperator();
		List<BaseEntity> itemList = new ArrayList<BaseEntity>();
		ArrayList<ArrayList<QueryObject>> allCriterias = (ArrayList<ArrayList<QueryObject>>) getFilter().createQueryCriterias();
		if (!isEmpty(allCriterias)) {
			if (!isEmpty(allCriterias.get(0))) {
				ArrayList<QueryObject> opsiyonelKriterler = new ArrayList<QueryObject>();
				if (!isEmpty(allCriterias.get(1))) {
					opsiyonelKriterler = allCriterias.get(1);
				}
				// setRecordCount(dbOperator.recordCountFiltered(getModelName(),
				// allCriterias.get(0), opsiyonelKriterler).intValue());
				setRecordCount(0);
				itemList = dbOperator.loadFiltered(getModelName(), allCriterias.get(0), opsiyonelKriterler, null, getOrderField());
				setListMessage(KeyUtil.getFrameworkLabel("list.toplam") + " " + getRecordCount() + " " + KeyUtil.getFrameworkLabel("kayit.bulundu"));
				setList(itemList);
				return;
			}
		}
		setRecordCount(dbOperator.recordCountAll(getModelName()).intValue());
		itemList = dbOperator.loadAll(getModelName(), null, getOrderField());
		setListMessage(KeyUtil.getFrameworkLabel("list.toplam") + " " + getRecordCount() + " " + KeyUtil.getFrameworkLabel("kayit.bulundu"));
		setList(itemList);
	}

}

Toys/JavaSource/tr/com/arf/toys/db/model/etkinlik/Etkinlik.java
package tr.com.arf.toys.db.model.etkinlik; 
 
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import tr.com.arf.framework.utility.tool.DateUtil;
import tr.com.arf.framework.utility.tool.KeyUtil;
import tr.com.arf.toys.db.enumerated.etkinlik.EtkinlikDurum;
import tr.com.arf.toys.db.model.base.ToysBaseEntity;
import tr.com.arf.toys.db.model.kisi.Donem;
import tr.com.arf.toys.db.model.kisi.Kisi;
import tr.com.arf.toys.db.model.system.Birim;
import tr.com.arf.toys.db.model.system.Ilce;
import tr.com.arf.toys.db.model.system.Sehir;
 
@Entity 
@Table(name = "ETKINLIK") 
public class Etkinlik extends ToysBaseEntity { 
 
	private static final long serialVersionUID = 1L; 
 
	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(updatable = false, unique = true, nullable = false, name = "RID") 
	private Long rID; 
 
	@ManyToOne 
	@JoinColumn(name = "ETKINLIKTANIMREF") 
	private Etkinliktanim etkinliktanimRef; 
 
	@ManyToOne 
	@JoinColumn(name = "BIRIMREF") 
	private Birim birimRef; 
	
	@ManyToOne 
	@JoinColumn(name = "DONEMREF") 
	private Donem donemRef;
	
	@Column(name = "AD") 
	private String ad; 
 
	@Temporal(TemporalType.DATE) 
	@Column(name = "BASLAMATARIH") 
	private java.util.Date baslamatarih; 
 
	@Temporal(TemporalType.DATE) 
	@Column(name = "BITISTARIH") 
	private java.util.Date bitistarih;
	
	@ManyToOne 
	@JoinColumn(name = "SEHIRREF") 
	private Sehir sehirRef; 
 
	@ManyToOne 
	@JoinColumn(name = "ILCEREF") 
	private Ilce ilceRef; 
 
	@Column(name = "YER") 
	private String yer; 
 
	@Column(name = "PROGRAM") 
	private String program; 

	@Column(name = "WEBADRESI") 
	private String webadresi; 
 
	@Column(name = "EPOSTAADRESI") 
	private String epostaadresi; 
 
	@Column(name = "TELEFONNO") 
	private String telefonno; 
 
	@ManyToOne 
	@JoinColumn(name = "SORUMLUKISIREF") 
	private Kisi sorumlukisiRef; 
 
	@Transient
	private Kisi sorumlukisiRefPrev;
	
	@Enumerated(EnumType.ORDINAL) 
	@Column(name = "DURUM") 
	private EtkinlikDurum durum; 
 
 
	public Etkinlik() { 
		super(); 
	} 
 
	@Override
	public Long getRID() { 
		return this.rID;  
	}  
	  
	@Override
	public void setRID(Long rID) {  
		this.rID = rID;  
	}   
 
	public Etkinliktanim getEtkinliktanimRef() { 
		return etkinliktanimRef; 
	} 
	 
	public void setEtkinliktanimRef(Etkinliktanim etkinliktanimRef) { 
		this.etkinliktanimRef = etkinliktanimRef; 
	} 
 
	public String getAd() { 
		return this.ad; 
	} 
	 
	public void setAd(String ad) { 
		this.ad = ad; 
	} 
 
	public java.util.Date getBaslamatarih() { 
		return baslamatarih; 
	} 
	 
	public void setBaslamatarih(java.util.Date baslamatarih) { 
		this.baslamatarih = baslamatarih; 
	}
	
	public java.util.Date getBitistarih() { 
		return bitistarih; 
	} 
	
	public void setBitistarih(java.util.Date bitistarih) { 
		this.bitistarih = bitistarih; 
	} 
 
	public Sehir getSehirRef() { 
		return sehirRef; 
	} 
	 
	public void setSehirRef(Sehir sehirRef) { 
		this.sehirRef = sehirRef; 
	} 
 
	public Birim getBirimRef() { 
		return birimRef; 
	} 
	
	public void setBirimRef(Birim birimRef) { 
		this.birimRef = birimRef; 
	}
	
	public Donem getDonemRef() { 
		return donemRef; 
	} 
	
	public void setDonemRef(Donem donemRef) { 
		this.donemRef = donemRef; 
	}
	
	public Ilce getIlceRef() { 
		return ilceRef; 
	} 
	 
	public void setIlceRef(Ilce ilceRef) { 
		this.ilceRef = ilceRef; 
	} 
 
	public String getYer() { 
		return this.yer; 
	} 
	 
	public void setYer(String yer) { 
		this.yer = yer; 
	} 
 
	public String getProgram() { 
		return this.program; 
	} 
	
	public void setProgram(String program) { 
		this.program = program; 
	}
	
	public String getWebadresi() { 
		return this.webadresi; 
	} 
	 
	public void setWebadresi(String webadresi) { 
		this.webadresi = webadresi; 
	} 
 
	public String getEpostaadresi() { 
		return this.epostaadresi; 
	} 
	 
	public void setEpostaadresi(String epostaadresi) { 
		this.epostaadresi = epostaadresi; 
	} 
 
	public String getTelefonno() { 
		return this.telefonno; 
	} 
	 
	public void setTelefonno(String telefonno) { 
		this.telefonno = telefonno; 
	} 
 
	public Kisi getSorumlukisiRef() { 
		return sorumlukisiRef; 
	} 
	 
	public void setSorumlukisiRef(Kisi sorumlukisiRef) { 
		this.sorumlukisiRef = sorumlukisiRef; 
	} 	
 
	public Kisi getSorumlukisiRefPrev() {
		return sorumlukisiRefPrev;
	}

	public void setSorumlukisiRefPrev(Kisi sorumlukisiRefPrev) {
		this.sorumlukisiRefPrev = sorumlukisiRefPrev;
	}

	public EtkinlikDurum getDurum() { 
		return this.durum;  
	}  
  
	public void setDurum(EtkinlikDurum durum) {  
		this.durum = durum;  
	}    
 
	@Override 
	public String toString() { 
		return etkinliktanimRef.getAd(); 
	} 
	@Override 
	public String getUIString() { 
		return getAd() + ""; 
	} 
	
	public boolean getDurumKontrol(){
		if(getDurum() == EtkinlikDurum._PLANLANMIS) {
			return false;
		}
		return true;
	}
	 
	@Override 
	public void initValues(boolean defaultValues) { 
			this.rID = null; 			this.etkinliktanimRef = null; 			this.ad = ""; 			this.baslamatarih = null; 			this.bitistarih = null; 			this.sehirRef = null; 			this.ilceRef = null; 			this.yer = ""; 			this.webadresi = ""; 			this.epostaadresi = ""; 			this.telefonno = ""; 			this.sorumlukisiRef = null; 			this.durum = EtkinlikDurum._NULL; 
			this.birimRef = null;			this.donemRef = null;
			this.program = null;	}  
	 
	@Override 
	public String getValue() {  
		StringBuilder value = new StringBuilder("Veri : <br />"); 
			if(getEtkinliktanimRef() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.etkinliktanimRef") + " : " + getEtkinliktanimRef().getUIString() + "<br />");
			} 
			if(getAd() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.ad") + " : " + getAd() + "<br />");
			} 
			if(getBaslamatarih() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.baslamatarih") + " : " + DateUtil.dateToDMYHMS(getBaslamatarih()) + "<br />");
			} 
			if(getBitistarih() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.bitistarih") + " : " + DateUtil.dateToDMYHMS(getBitistarih()) + "<br />");
			} 
			if(getSehirRef() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.sehirRef") + " : " + getSehirRef().getUIString() + "<br />");
			} 
			if(getIlceRef() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.ilceRef") + " : " + getIlceRef().getUIString() + "<br />");
			} 
			if(getYer() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.yer") + " : " + getYer() + "<br />");
			} 
			if(getProgram() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.program") + " : " + getProgram() + "<br />");
			} 
			if(getWebadresi() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.webadresi") + " : " + getWebadresi() + "<br />");
			} 
			if(getEpostaadresi() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.epostaadresi") + " : " + getEpostaadresi() + "<br />");
			} 
			if(getTelefonno() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.telefonno") + " : " + getTelefonno() + "<br />");
			} 
			if(getSorumlukisiRef() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.sorumlukisiRef") + " : " + getSorumlukisiRef().getUIString() + "<br />");
			} 
			if(getDurum() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.durum") + " : " + getDurum().getLabel() + "");
			} 
			if(getBirimRef() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.birimRef") + " : " + getBirimRef() + "");
			} 
			if(getDonemRef() != null) {
				value.append(KeyUtil.getLabelValue("etkinlik.donemRef") + " : " + getDonemRef() + "");
			} 
		return value.toString(); 
	} 
	 
}	 

Toys/JavaSource/tr/com/arf/toys/db/model/etkinlik/Etkinliktanim.java
package tr.com.arf.toys.db.model.etkinlik;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import tr.com.arf.framework.db.enumerated._common.EvetHayir;
import tr.com.arf.framework.utility.tool.KeyUtil;
import tr.com.arf.toys.db.model.base.ToysBaseEntity;

@Entity
@Table(name = "ETKINLIKTANIM")
public class Etkinliktanim extends ToysBaseEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(updatable = false, unique = true, nullable = false, name = "RID")
	private Long rID;

	@Column(name = "AD")
	private String ad;

	@Enumerated(EnumType.ORDINAL)
	@Column(name = "PERIYODIK")
	private EvetHayir periyodik;

	@Column(name = "ACIKLAMA")
	private String aciklama;

	@Column(name = "ANAHTARKELIMELER")
	private String anahtarkelimeler;

	public Etkinliktanim() {
		super();
	}

	@Override
	public Long getRID() {
		return this.rID;
	}

	@Override
	public void setRID(Long rID) {
		this.rID = rID;
	}

	public String getAd() {
		return this.ad;
	}

	public void setAd(String ad) {
		this.ad = ad;
	}

	public EvetHayir getPeriyodik() {
		return this.periyodik;
	}

	public void setPeriyodik(EvetHayir periyodik) {
		this.periyodik = periyodik;
	}

	public String getAciklama() {
		return this.aciklama;
	}

	public void setAciklama(String aciklama) {
		this.aciklama = aciklama;
	}

	public String getAnahtarkelimeler() {
		return anahtarkelimeler;
	}

	public void setAnahtarkelimeler(String anahtarkelimeler) {
		this.anahtarkelimeler = anahtarkelimeler;
	}

	@Override
	public String toString() {
		return "tr.com.arf.toys.db.model.etkinlik.Etkinliktanim[id="
				+ this.getRID() + "]";
	}

	@Override
	public String getUIString() {
		return getAd() + "";
	}

	@Override
	public void initValues(boolean defaultValues) {
		this.rID = null;
		this.ad = "";
		this.periyodik = EvetHayir._NULL;
		this.aciklama = "";
		this.anahtarkelimeler = "";
	}

	@Override
	public String getValue() {
		StringBuilder value = new StringBuilder("Veri : <br />");
		if (getAd() != null) {
			value.append(KeyUtil.getLabelValue("etkinliktanim.ad") + " : "
					+ getAd() + "<br />");
		}
		if (getPeriyodik() != null) {
			value.append(KeyUtil.getLabelValue("etkinliktanim.periyodik")
					+ " : " + getPeriyodik().getLabel() + "<br />");
		}
		if (getAciklama() != null) {
			value.append(KeyUtil.getLabelValue("etkinliktanim.aciklama")
					+ " : " + getAciklama() + "");
		}
		if (getAnahtarkelimeler() != null) {
			value.append(KeyUtil.getLabelValue("etkinliktanim.anahtarkelimeler")
					+ " : " + getAnahtarkelimeler() + "");
		}
		return value.toString();
	}

	public boolean getGoster() {
		if (periyodik == EvetHayir._NULL) {
			return false;
		}
		if (periyodik == EvetHayir._EVET) {
			return false;
		}
		return true;
	}
}

Toys/WebContent/_page/form/etkinlik/etkinliktanim_Edit.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:arf="http://java.sun.com/jsf/composite/arfComposite" xmlns:arftags="http://arf.com/column">

	<p:fieldset id="etkinliktanimEditPanel" toggleable="false" styleClass="pageFieldSet" legend="#{label['etkinliktanim.edit']}"
		rendered="#{etkinliktanimController.editPanelRendered}">
		<h:panelGrid columns="2" columnClasses="elliYuzde, elliYuzde" styleClass="arfEditGrid">

			<arf:textinput label="#{label['etkinliktanim.ad']}" value="#{etkinliktanimController.etkinliktanim.ad}" compId="ad" requiredCond="true" id="adInputText" maxLength="200" />

			<arf:dropdown label="#{label['etkinliktanim.periyodik']}" listSource="#{enumeratedController.evetHayirItems}" requiredCond="true" compId="periyodik"
				value="#{etkinliktanimController.etkinliktanim.periyodik}" id="periyodikDropDown" addNullOption="false" ajaxEventListener="#{etkinliktanimController.handleChange}"
				changeEventUpdateComp="#{':etkinliktanimForm:inputPanel'}" />

			<arf:textinputarea label="#{label['etkinliktanim.genelbilgi']}" value="#{etkinliktanimController.etkinliktanim.aciklama}" compId="aciklama" requiredCond="false"
				id="aciklamaInputText" maxLength="2500" />

			<arf:textinputarea label="#{label['etkinliktanim.anahtarkelimeler']}" value="#{etkinliktanimController.etkinliktanim.anahtarkelimeler}" compId="anahtarkelimeler"
				requiredCond="true" id="anahtarkelimelerInputText" maxLength="1000" />

		</h:panelGrid>
		<p:outputPanel id="inputPanel">
			<p:fieldset id="etkinlikEditPanel" toggleable="false" styleClass="pageFieldSet" legend="#{label['etkinlik.edit']}"
				rendered="#{etkinliktanimController.etkinliktanim.goster}">
				<h:panelGrid columns="2" columnClasses="elliYuzde, elliYuzde" styleClass="arfEditGrid">

					<arf:dropdown label="#{label['etkinlik.birimRef']}" listSource="#{sessionUser.birimItemList}" requiredCond="true" compId="birimRef"
						value="#{etkinliktanimController.etkinlik.birimRef}" converterId="#{'birimConverter'}" id="birimRefDropDown" />

					<arf:dropdown label="#{label['etkinlik.donemRef']}" listSource="#{etkinliktanimController.selectItemListFor('Donem')}" requiredCond="true" compId="donemRef"
						value="#{etkinliktanimController.etkinlik.donemRef}" converterId="#{'donemConverter'}" id="donemRefDropDown" />

					<arf:calendar label="#{label['etkinlik.baslamatarih']}" value="#{etkinliktanimController.etkinlik.baslamatarih}" id="baslamatarihCalendar"
						pattern="#{configurationController.datePattern}" requiredCond="true" compId="baslamactarih" />

					<arf:calendar label="#{label['etkinlik.bitistarih']}" value="#{etkinliktanimController.etkinlik.bitistarih}" id="bitistarihCalendar"
						pattern="#{configurationController.datePattern}" requiredCond="true" compId="bitistarih" />

					<arf:dropdown label="#{label['etkinlik.sehirRef']}" listSource="#{sessionUser.sehirItemList}" requiredCond="true" compId="sehirRef"
						value="#{etkinliktanimController.etkinlik.sehirRef}" converterId="#{'sehirConverter'}" id="sehirRefDropDown" ajaxEventListener="#{etkinliktanimController.handleChange}"
						changeEventUpdateComp="#{':etkinliktanimForm:ilceRefDropDown:ilceRef'}" />

					<arf:dropdown label="#{label['birim.ilceRef']}" listSource="#{etkinliktanimController.ilceItemList}" requiredCond="true" compId="ilceRef"
						value="#{etkinliktanimController.etkinlik.ilceRef}" converterId="#{'ilceConverter'}" id="ilceRefDropDown" />

					<arf:textinputarea label="#{label['etkinlik.yer']}" value="#{etkinliktanimController.etkinlik.yer}" compId="yer" requiredCond="true" id="yerInputText" maxLength="2500" />

					<arf:textinputarea label="#{label['etkinlik.program']}" value="#{etkinliktanimController.etkinlik.program}" compId="program" requiredCond="true" id="programInputText"
						maxLength="5000" />

					<arf:textinput label="#{label['etkinlik.webadresi']}" value="#{etkinliktanimController.etkinlik.webadresi}" compId="webadresi" requiredCond="false"
						id="webadresiInputText" maxLength="500" />

					<arf:textinput label="#{label['etkinlik.epostaadresi']}" value="#{etkinliktanimController.etkinlik.epostaadresi}" compId="epostaadresi" requiredCond="false"
						id="epostaadresiInputText" maxLength="500" />

					<arf:textinput label="#{label['etkinlik.telefonno']}" value="#{etkinliktanimController.etkinlik.telefonno}" compId="telefonno" requiredCond="false"
						id="telefonnoInputText" maxLength="500" />

					<arf:suggestbox label="#{label['etkinlik.sorumlukisiRef']}" methodName="#{etkinliktanimController.completeMethod}" requiredCond="false" compId="sorumlukisiRef"
						value="#{etkinliktanimController.etkinlik.sorumlukisiRef}" id="sorumlukisiRefSuggestBox" converterId="#{'kisiConverter'}" modelName="#{'Kisi'}" var="sorumluRec"
						itemValue="#{sorumluRec}" itemLabel="#{sorumluRec}" />

					<arf:dropdown label="#{label['etkinlik.durum']}" listSource="#{enumeratedController.etkinlikDurumItems}" requiredCond="true" compId="durum"
						value="#{etkinliktanimController.etkinlik.durum}" id="durumDropDown" addNullOption="false" />

				</h:panelGrid>

			</p:fieldset>
		</p:outputPanel>
		<arf:editPanelBottomWithBlockUI controllerClassName="#{etkinliktanimController}" formName="etkinliktanimForm" listPanelName="etkinliktanimListPanel"
			editPanelName="etkinliktanimEditPanel" modelName="Etkinliktanim" />
	</p:fieldset>


</ui:composition>