Toys/JavaSource/tr/com/arf/framework/view/controller/form/_base/BaseController.java
package tr.com.arf.framework.view.controller.form._base;

import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.Serializable;
import java.math.MathContext;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.html.HtmlSelectOneMenu;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.model.SelectItem;

import org.apache.log4j.Logger;
import org.primefaces.component.datatable.DataTable;
import org.primefaces.component.selectonemenu.SelectOneMenu;
import org.primefaces.context.RequestContext;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.event.ToggleEvent;
import org.primefaces.model.DualListModel;
import org.primefaces.model.UploadedFile;
import org.primefaces.model.Visibility;

import tr.com.arf.framework.db._management.DBOperator;
import tr.com.arf.framework.db.enumerated._common.EvetHayir;
import tr.com.arf.framework.db.enumerated._common.IslemTuru;
import tr.com.arf.framework.db.model._base.BaseEntity;
import tr.com.arf.framework.db.model.sistem.Islemlog;
import tr.com.arf.framework.utility.application.ApplicationConstantBase;
import tr.com.arf.framework.utility.application.ApplicationDescriptorBase;
import tr.com.arf.framework.utility.exception.data.DBException;
import tr.com.arf.framework.utility.tool.DateUtil;
import tr.com.arf.framework.utility.tool.KeyUtil;
import tr.com.arf.framework.utility.tool.RandomObjectGenerator;
import tr.com.arf.framework.view.controller._common.SessionUserBase;

public abstract class BaseController implements Serializable {

	private static final long serialVersionUID = 3483304400136924177L;

	private BaseEntity[] selection;

	private boolean addScreen;
	private BaseEntity entity;
	private String orderField;
	private DataTable table;
	private DataTable logTable;
	private javax.faces.component.html.HtmlDataTable treeTable;

	private boolean defaultValues;

	private String oldValue;

	protected String selectedRID = null;

	private List<BaseEntity> filteredList;
	private boolean editPanelRendered;

	protected String[] autoCompleteSearchColumns;
	private String modelName;
	private String className;

	private int currentPage;
	private int listSize = 10;
	private int recordCount;

	private String selectedTabName;
	private String listMessage = "";

	private String staticWhereCondition = "";

	/* Data Operator */
	private DBOperator dBOperator;
	private List<BaseEntity> list;

	/* LOG */
	protected boolean loggable;

	/* Math Context For BigDecimals */
	protected MathContext mc = MathContext.DECIMAL32;

	/* Log4j Logger */
	protected static Logger logger = Logger.getLogger("commonController");

	/*
	 * File Upload listener kullanilmasi gibi durumlarda edit (ekleme/guncelleme) 2 adimda yapilir. Edit step bu amacla kullanilir.
	 */
	private int editStep = 1;

	protected BaseController(@SuppressWarnings("rawtypes") Class c) {
		setOrderField("");
		setOldValue("");
		setModelName(c.getSimpleName());
		setClassName(c.getName());
		setDefaultValues(false);
		setEditPanelRendered(false);
		setCurrentPage(1);
		setRecordCount(0);
		cancel();
		setLoggable(false);
		setLogTable(null);
		setListMessage("");
		setListSize(ApplicationConstantBase._LIST_SIZE);
		this.collapsed = false;
	}

	@PostConstruct
	public void init() {
		if (getObjectFromSessionFilter(getModelName()) != null) {
			setEntity((BaseEntity) getObjectFromSessionFilter(getModelName()));
		}
	}

	public SessionUserBase getSessionUser() {
		Map<String, Object> sessionMap = FacesContext.getCurrentInstance().getExternalContext().getSessionMap();
		return (SessionUserBase) sessionMap.get("sessionUser");
	}

	public List<BaseEntity> getList() {
		return list;
	}

	public void setList(List<BaseEntity> list) {
		this.list = list;
	}

	public int getEditStep() {
		return editStep;
	}

	public void setEditStep(int editStep) {
		this.editStep = editStep;
	}

	public String getModelName() {
		return modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	public boolean isListRendered() {
		return true;
	}

	public boolean listRenderedFor(String modelName) {
		return true;
	}

	public boolean isUpdateRecordRendered() {
		return true;
	}

	public boolean updateRecordRenderedFor(String modelName) {
		return true;
	}

	public boolean isDeleteRendered() {
		return true;
	}

	public boolean deleteRenderedFor(String modelName) {
		return true;
	}

	/* Data Operator */
	protected final DBOperator getDBOperator() {
		if (dBOperator == null) {
			dBOperator = DBOperator.getInstance();
		}
		return dBOperator;
	}

	@SuppressWarnings("unchecked")
	public void queryAction() {
		// List<BaseEntity> itemList = new ArrayList<BaseEntity>();
		setRecordCount(getDBOperator().recordCountAll(getModelName()).intValue());
		setList(getDBOperator().loadAll(getModelName(), getRecordInterval(), getOrderField()));
		setListMessage(KeyUtil.getFrameworkLabel("list.toplam") + " " + getRecordCount() + " " + KeyUtil.getFrameworkLabel("kayit.bulundu"));
		// setList(itemList);
		setEditStep(1);
	}

	public DataTable getTable() {
		return table;
	}

	public void setTable(DataTable table) {
		this.table = table;
	}

	public DataTable getLogTable() {
		return logTable;
	}

	public void setLogTable(DataTable logTable) {
		this.logTable = logTable;
	}

	public javax.faces.component.html.HtmlDataTable getTreeTable() {
		return treeTable;
	}

	public void setTreeTable(javax.faces.component.html.HtmlDataTable treeTable) {
		this.treeTable = treeTable;
	}

	public boolean isAddScreen() {
		return addScreen;
	}

	public void setAddScreen(boolean addScreen) {
		this.addScreen = addScreen;
	}

	public String getOldValue() {
		return oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	public BaseEntity[] getSelection() {
		return selection;
	}

	public void setSelection(BaseEntity[] selection) {
		this.selection = selection;
	}

	public BaseEntity getEntity() {
		return entity;
	}

	public void setEntity(BaseEntity entity) {
		this.entity = entity;
	}

	protected String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getOrderField() {
		return orderField;
	}

	public void setOrderField(String orderField) {
		this.orderField = orderField;
	}

	protected boolean isDefaultValues() {
		return defaultValues;
	}

	protected void setDefaultValues(boolean defaultValues) {
		this.defaultValues = defaultValues;
	}

	public String getListOutcome() {
		return getModelName().toLowerCase(Locale.ENGLISH) + ".do";
	}

	public String getEditOutcome() {
		String result = getModelName().toLowerCase(Locale.ENGLISH) + ApplicationConstantBase._EDIT_SUFFIX + ".do";
		return result;
	}

	protected String getExceptionOutcome() {
		return ApplicationDescriptorBase._EXCEPTION_OUTCOME;
	}

	@SuppressWarnings("unchecked")
	public SelectItem[] getSelectItemList() {
		List<BaseEntity> entityList = getDBOperator().load(getModelName(), getStaticWhereCondition(), "o.rID");
		if (entityList != null) {
			SelectItem[] selectItemList = new SelectItem[entityList.size() + 1];
			selectItemList[0] = new SelectItem(null, "");
			int i = 1;
			for (BaseEntity entity : entityList) {
				selectItemList[i++] = new SelectItem(entity, entity.getUIString());
			}
			return selectItemList;
		}
		return new SelectItem[0];
	}

	public SelectItem[] selectItemListForWithoutNullOption(String modelNameForSelectItems) {
		String staticWhereCon = getStaticWhereCondition();
		if (!modelNameForSelectItems.equalsIgnoreCase(getModelName())) {
			staticWhereCon = getStaticWhereCondition(modelNameForSelectItems);
		}
		return createSelectItems(modelNameForSelectItems, staticWhereCon, false);
	}

	public SelectItem[] selectItemListFor(String modelNameForSelectItems) {
		String staticWhereCon = getStaticWhereCondition();
		if (!modelNameForSelectItems.equalsIgnoreCase(getModelName())) {
			staticWhereCon = getStaticWhereCondition(modelNameForSelectItems);
		}
		return createSelectItems(modelNameForSelectItems, staticWhereCon, true);
	}

	public SelectItem[] selectOrderedItemListFor(String modelNameForSelectItems, String orderField) {
		String staticWhereCon = getStaticWhereCondition();
		if (!modelNameForSelectItems.equalsIgnoreCase(getModelName())) {
			staticWhereCon = getStaticWhereCondition(modelNameForSelectItems);
		}
		return createSelectItems(modelNameForSelectItems, staticWhereCon, true, orderField);
	}

	public SelectItem[] selectOrderedItemListWithoutNullOptionFor(String modelNameForSelectItems, String orderField) {
		String staticWhereCon = getStaticWhereCondition();
		if (!modelNameForSelectItems.equalsIgnoreCase(getModelName())) {
			staticWhereCon = getStaticWhereCondition(modelNameForSelectItems);
		}
		return createSelectItems(modelNameForSelectItems, staticWhereCon, false, orderField);
	}

	public SelectItem[] selectItemListFor(String modelNameForSelectItems, String whereCondition) {
		return createSelectItems(modelNameForSelectItems, whereCondition, true);
	}

	public SelectItem[] selectItemListForWithoutNullOption(String modelNameForSelectItems, String whereCondition) {
		return createSelectItems(modelNameForSelectItems, whereCondition, false);
	}

	public SelectItem[] createSelectItems(String modelNameForSelectItems, String whereCondition, boolean nullOption) {
		return createSelectItems(modelNameForSelectItems, whereCondition, nullOption, "");
	}

Toys/JavaSource/tr/com/arf/toys/db/model/iletisim/IletisimListeUye.java
package tr.com.arf.toys.db.model.iletisim; 
 
public class IletisimListeUye {
	
	private String uyeler;

	public String getUyeler() {
		return uyeler;
	}

	public void setUyeler(String uyeler) {
		this.uyeler = uyeler;
	}
	 
}

Toys/JavaSource/tr/com/arf/toys/db/model/iletisim/Iletisimliste.java
package tr.com.arf.toys.db.model.iletisim; 
 
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import tr.com.arf.framework.db.model._base.BaseTreeEntity;
import tr.com.arf.framework.utility.tool.KeyUtil;
import tr.com.arf.toys.db.enumerated.iletisim.ListeGizlilikTuru;
import tr.com.arf.toys.db.enumerated.iletisim.ReferansTipi;
import tr.com.arf.toys.db.model.base.ToysBaseTreeEntity;
import tr.com.arf.toys.db.model.system.Birim;
import tr.com.arf.toys.service.application.ApplicationDescriptor;
 
@Entity 
@Table(name = "ILETISIMLISTE") 
public class Iletisimliste extends ToysBaseTreeEntity { 
 
	private static final long serialVersionUID = 1L; 
 
	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(updatable = false, unique = true, nullable = false, name = "RID") 
	private Long rID; 
 
	@Column(name = "AD") 
	private String ad; 
 
	@ManyToOne 
	@JoinColumn(name = "USTREF") 
	private Iletisimliste ustRef; 
 
	@Column(name = "ERISIMKODU") 
	private String erisimKodu; 
 
	@ManyToOne 
	@JoinColumn(name = "BIRIMREF") 
	private Birim birimRef; 
 
	@Enumerated(EnumType.ORDINAL) 
	@Column(name = "LISTEGIZLILIKTURU") 
	private ListeGizlilikTuru listegizlilikturu; 
 
	@Column(name = "ACIKLAMA") 
	private String aciklama; 
 
 
	public Iletisimliste() { 
		super(); 
	} 
 
	@Override
	public Long getRID() { 
		return this.rID;  
	}  
	  
	@Override
	public void setRID(Long rID) {  
		this.rID = rID;  
	}   
 
	@Override
	public String getAd() { 
		return this.ad; 
	} 
	 
	@Override
	public void setAd(String ad) { 
		this.ad = ad; 
	} 
 
	@Override 
	public Iletisimliste getUstRef() { 
		return ustRef; 
	} 
	 
	@Override 
	public void setUstRef(BaseTreeEntity ustRef) {  
		if(getUstRef() == null) {
			this.ustRef = (Iletisimliste) ustRef;
		} 
	} 
	 
	public void setUstRef(Iletisimliste ustRef) { 
		this.ustRef = ustRef; 
	} 
 
	@Override
	public String getErisimKodu() { 
		return this.erisimKodu; 
	} 
	 
	@Override
	public void setErisimKodu(String erisimKodu) { 
		this.erisimKodu = erisimKodu; 
	} 
 
	public Birim getBirimRef() { 
		return birimRef; 
	} 
	 
	public void setBirimRef(Birim birimRef) { 
		this.birimRef = birimRef; 
	} 
 
	public ListeGizlilikTuru getListegizlilikturu() { 
		return this.listegizlilikturu;  
	}  
  
	public void setListegizlilikturu(ListeGizlilikTuru listegizlilikturu) {  
		this.listegizlilikturu = listegizlilikturu;  
	}   
 
	public String getAciklama() { 
		return this.aciklama; 
	} 
	 
	public void setAciklama(String aciklama) { 
		this.aciklama = aciklama; 
	} 
	
	@SuppressWarnings({ "unchecked" })
	@Transient
	public int getIletisimKisiSayisi(){
		int kisisayisi=0;
		if(getRID() == null) {
			return 0;
		} else {
			try {
				if(getDBOperator().recordCount(Iletisimlistedetay.class.getSimpleName(), "o.iletisimlisteRef.rID=" + getRID()) > 0){
					List <Iletisimlistedetay> iletisimList =getDBOperator().load(Iletisimlistedetay.class.getSimpleName(), "o.iletisimlisteRef.rID=" + getRID(),"");
					for (Iletisimlistedetay entity : iletisimList){
						if (entity.getReferansTipi()==ReferansTipi._KISI){
							kisisayisi++;
						}
						if (entity.getReferansTipi() == ReferansTipi._UYE){
							kisisayisi++;
						}
						if (entity.getReferansTipi()== ReferansTipi._KURUM){
							kisisayisi++;
						}
						if (entity.getReferansTipi()== ReferansTipi._EGITMEN){
							kisisayisi++;
						}
						if (entity.getReferansTipi()== ReferansTipi._ISYERITEMSILCISI){
							kisisayisi++;
						}
						if (entity.getReferansTipi()== ReferansTipi._BIRIM){
							kisisayisi+=getDBOperator().recordCount(ApplicationDescriptor._UYE_MODEL,"o.birimRef.rID="+ entity.getReferans());
						}
						if(entity.getReferansTipi()== ReferansTipi._KURUL){
							kisisayisi+=getDBOperator().recordCount(ApplicationDescriptor._KURULDONEMUYE_MODEL,"o.kurulDonemRef.rID=" + entity.getReferans());
						}
						if(entity.getReferansTipi()== ReferansTipi._KOMISYON){
							kisisayisi+=getDBOperator().recordCount(ApplicationDescriptor._KOMISYONDONEMUYE_MODEL,"o.komisyonDonemRef.rID=" + entity.getReferans());
						}
						if(entity.getReferansTipi()== ReferansTipi._ETKINLIKKATILIMCI){
							kisisayisi+=getDBOperator().recordCount(ApplicationDescriptor._ETKINLIKKATILIMCI_MODEL,"o.etkinlikRef.rID=" + entity.getReferans());
						}
						if(entity.getReferansTipi()== ReferansTipi._EGITIMKATILIMCI){
							kisisayisi+=getDBOperator().recordCount(ApplicationDescriptor._EGITIMKATILIMCI_MODEL,"o.egitimRef.rID=" + entity.getReferans());
						}
					}
					return kisisayisi;
				}
			} catch (Exception e) { 
				e.printStackTrace();
				return kisisayisi;
			}			
		}
		return kisisayisi;
	}
 
 
	@Override 
	public String toString() { 
		return this.getAd();
	} 
	@Override 
	public String getUIString() { 
		String result = getAd() + ""; 
	/*	if (getUstRef() != null) { 
			result += " / " + getUstRef().getAd() + "" ; 
		} */
		return result; 
	} 
	 
	@Override 
	public void initValues(boolean defaultValues) { 
			this.rID = null; 			this.ad = ""; 			this.ustRef = null; 			this.erisimKodu = ""; 			this.birimRef = null; 			this.listegizlilikturu = ListeGizlilikTuru._NULL; 			this.aciklama = ""; 	}  
	 
	@Override 
	public String getValue() {  
		StringBuilder value = new StringBuilder("Veri : <br />"); 
			if(getAd() != null) {
				value.append(KeyUtil.getLabelValue("iletisimliste.ad") + " : " + getAd() + "<br />");
			} 
			if(getUstRef() != null) {
				value.append(KeyUtil.getLabelValue("iletisimliste.ustRef") + " : " + getUstRef().getUIString() + "<br />");
			} 
			if(getErisimKodu() != null) {
				value.append(KeyUtil.getLabelValue("iletisimliste.erisimKodu") + " : " + getErisimKodu() + "<br />");
			} 
			if(getBirimRef() != null) {
				value.append(KeyUtil.getLabelValue("iletisimliste.birimRef") + " : " + getBirimRef().getUIString() + "<br />");
			} 
			if(getListegizlilikturu() != null) {
				value.append(KeyUtil.getLabelValue("iletisimliste.listegizlilikturu") + " : " + getListegizlilikturu().getLabel() + "<br />");
			} 
			if(getAciklama() != null) {
				value.append(KeyUtil.getLabelValue("iletisimliste.aciklama") + " : " + getAciklama() + "");
			} 
		return value.toString(); 
	} 
	 
}	 

Toys/WebContent/_page/form/iletisim/iletisimliste.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:arf="http://java.sun.com/jsf/composite/arfComposite" xmlns:arftags="http://arf.com/column" template="/_page/_main/main.xhtml">

	<ui:define name="content">
		<h:body>
			<h:form id="iletisimlisteForm" prependId="false">
				<ui:include src="/_page/form/iletisim/iletisimliste_Edit.xhtml" />

				<p:fieldset id="iletisimlisteFilterPanel" toggleable="true" styleClass="pageFieldSet" collapsed="#{iletisimlisteController.collapsed}"
					legend="#{label['iletisimliste.query']}" rendered="#{!iletisimlisteController.editPanelRendered}">
					<p:ajax listener="#{iletisimlisteController.onToggle}" event="toggle" />
					<h:panelGrid columns="3" columnClasses="otuzUcYuzde, otuzUcYuzde, otuzUcYuzde" styleClass="arfEditGrid">
						<arf:textinputForFilter label="#{label['iletisimliste.ad']}" value="#{iletisimlisteController.iletisimlisteFilter.ad}" compId="ad" requiredCond="false"
							id="adForFilterInputText" maxLength="100" />

						<arf:dropdownForFilter label="#{label['iletisimliste.ustRef']}" listSource="#{iletisimlisteController.selectItemListFor('Iletisimliste')}" requiredCond="false"
							compId="ustRef" value="#{iletisimlisteController.iletisimlisteFilter.ustRef}" converterId="#{'iletisimlisteConverter'}" id="ustRefForFilterDropDown"
							addNullOption="true" />

						<arf:dropdownForFilter label="#{label['iletisimliste.birimRef']}" listSource="#{sessionUser.birimItemList}" requiredCond="false"
							compId="birimRef" value="#{iletisimlisteController.iletisimlisteFilter.birimRef}" converterId="#{'birimConverter'}" id="birimRefForFilterDropDown" />

						<arf:dropdownForFilter label="#{label['iletisimliste.listegizlilikturu']}" listSource="#{enumeratedController.listeGizlilikTuruItems}" requiredCond="false"
							compId="listegizlilikturu" value="#{iletisimlisteController.iletisimlisteFilter.listegizlilikturu}" id="listegizlilikturuForFilterDropDown" addNullOption="true" />

					</h:panelGrid>

					<arf:filterBottomWithBlockUI controllerClassName="#{iletisimlisteController}" formName="iletisimlisteForm" listPanelName="iletisimlisteListPanel"
						filterPanelName="iletisimlisteFilterPanel" modelName="Iletisimliste" />
				</p:fieldset>

				<div id="divleft">
					<p:fieldset legend="#{label['iletisimliste.list']}" styleClass="pageFieldSet" id="iletisimlisteListPanel">
						<h:panelGrid columns="10" border="0" style="text-align:center" cellspacing="0" cellpadding="0">
							<p:commandButton id="iletisimlistedetayCommand" process="@this" icon="child" action="#{iletisimlisteController.iletisimlistedetay}"
								rendered="#{iletisimlisteController.listRenderedFor('Iletisimlistedetay')}" disabled="#{iletisimlisteController.iletisimliste.RID == null}"
								value="#{label['command.iletisimlistedetay']}" styleClass="arfCommandButton" />

							<p:commandButton id="iletisimlisteTreeCommand" process="@this" action="#{iletisimlisteController.treePage}" icon="tree"
								rendered="#{iletisimlisteController.listRendered}" value="#{label['iletisimliste.tree']}" styleClass="arfCommandButton" />
								
							<p:commandButton id="iletisimlistedetayCommand1" process="@this" icon="uye" action="#{iletisimlisteController.listeuyeleri}"
								rendered="#{iletisimlisteController.listRenderedFor('Iletisimlistedetay')}" value="#{label['command.listeuye']}" styleClass="arfCommandButton" />
								
							<p:commandButton id="epostaGonderCommand" process="@this" icon="adres" action="#{iletisimlisteController.epostagonder}"
								rendered="#{iletisimlisteController.listRenderedFor('Iletisimlistedetay')}" disabled="#{iletisimlisteController.iletisimliste.RID == null}"
								value="#{label['command.epostagonder']}" styleClass="arfCommandButton" />
								
							<p:commandButton id="smsGonderCommand" process="@this" icon="adres" action="#{iletisimlisteController.smsgonder}"
								rendered="#{iletisimlisteController.listRenderedFor('Iletisimlistedetay')}" disabled="#{iletisimlisteController.iletisimliste.RID == null}"
								value="#{label['command.smsgonder']}" styleClass="arfCommandButton" />
								
						</h:panelGrid>
						<p:blockUI block="iletisimlisteTable" trigger="iletisimlisteTable">
							<h:outputText value="#{label['common.loading']}" />
							<br />
							<h:graphicImage library="_image" name="ajax-loader.gif" />
						</p:blockUI>
						<p:dataTable emptyMessage="#{label['primefaces.noRecordFound']}" style="margin-top:10px" id="iletisimlisteTable" value="#{iletisimlisteController.list}" var="iletisimlisteRow" binding="#{iletisimlisteController.table}"
							rowIndexVar="rowIndex" selectionMode="single" selection="#{iletisimlisteController.entity}" filteredValue="#{iletisimlisteController.filteredList}"
							widgetVar="filterTable" rowKey="#{iletisimlisteRow.RID}" resizableColumns="false">

							<p:ajax event="rowSelect" listener="#{iletisimlisteController.tableRowSelect}" update=":iletisimlisteForm" />
							<p:ajax event="rowUnselect" listener="#{iletisimlisteController.tableRowCancelSelection}" update=":iletisimlisteForm" />

							<arftags:column val="#{iletisimlisteRow.ad}" header="#{label['iletisimliste.ad']}" width="16" />
							<arftags:column val="#{iletisimlisteRow.ustRef.UIString}" header="#{label['iletisimliste.ustRef']}" width="16" />
							<arftags:column val="#{iletisimlisteRow.birimRef.UIString}" header="#{label['iletisimliste.birimRef']}" width="16" />
							<arftags:column val="#{iletisimlisteRow.listegizlilikturu.label}" header="#{label['iletisimliste.listegizlilikturu']}" width="16" />
							<arftags:column val="#{iletisimlisteRow.aciklama}" header="#{label['iletisimliste.aciklama']}" width="16" />
							<arftags:column val="#{iletisimlisteRow.iletisimKisiSayisi}" header="#{label['iletisimliste.kisisayisi']}" width="10" />
						</p:dataTable>

						<arf:pagingWithBlockUI controllerClassName="#{iletisimlisteController}" formName="iletisimlisteForm" listPanelName="iletisimlisteListPanel" pagingOption="true"
							tableName="iletisimlisteTable" addExport="true" addOption="true" updateOption="true" deleteOption="true" addSubRecordOption="false" exportToWord="false" />
					</p:fieldset>

				</div>
				<div id="divright">
					<p:fieldset id="iletisimlisteSummaryPanel" toggleable="false" styleClass="pageFieldSet" legend="#{label['iletisimliste.summary']}"
						rendered="#{iletisimlisteController.iletisimliste.RID != null}">
						<h:panelGrid columns="2" columnClasses="otuzYuzde, yetmisYuzde" style="width:100%">
						</h:panelGrid>
						<p:panel header="#{label['iletisimlistedetay.list']}" style="width:100%" rendered="#{iletisimlisteController.iletisimliste.RID != null}">
							<ui:repeat value="#{iletisimlisteController.list}" var="iletisimlistedetay">
								<li><h:outputText value="#{iletisimlistedetay.UIString}" /></li>
							</ui:repeat>
						</p:panel>
					</p:fieldset>
				</div>
			</h:form>
		</h:body>
	</ui:define>
</ui:composition>

Toys/WebContent/_page/form/iletisim/iletisimliste_Tree.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:arf="http://java.sun.com/jsf/composite/arfComposite" template="/_page/_main/main.xhtml">

	<ui:define name="content">
		<h:body>
			<h:form id="iletisimlisteForm" prependId="false">

				<ui:include src="/_page/form/iletisim/iletisimliste_Edit.xhtml" />

				<arf:treePage controllerClassName="#{iletisimlisteController}" formName="iletisimlisteForm" panelName="iletisimlisteTreePanel" modelName="iletisimliste"
					listLabel="#{label['iletisimliste.list']}" treeLabel="#{label['iletisimliste.tree']}" />
			</h:form>
		</h:body>
	</ui:define>
</ui:composition>