Toys/JavaSource/tr/com/arf/toys/db/model/uye/Uye.java
package tr.com.arf.toys.db.model.uye;

import tr.com.arf.framework.db._management.DBOperator;
import tr.com.arf.framework.db.enumerated._common.EvetHayir;
import tr.com.arf.framework.utility.tool.DateUtil;
import tr.com.arf.framework.utility.tool.KeyUtil;
import tr.com.arf.toys.db.enumerated.iletisim.AdresTuru;
import tr.com.arf.toys.db.enumerated.uye.*;
import tr.com.arf.toys.db.model.base.ToysBaseEntity;
import tr.com.arf.toys.db.model.iletisim.Adres;
import tr.com.arf.toys.db.model.kisi.Kisi;
import tr.com.arf.toys.db.model.kisi.Kisikimlik;
import tr.com.arf.toys.db.model.kisi.Kisiogrenim;
import tr.com.arf.toys.db.model.kisi.Kurum;
import tr.com.arf.toys.db.model.system.Birim;
import tr.com.arf.toys.db.model.system.KurumKisi;
import tr.com.arf.toys.db.model.system.Personel;
import tr.com.arf.toys.service.application.ManagedBeanLocator;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

@Entity
@Table(name = "UYE")
public class Uye extends ToysBaseEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(updatable = false, unique = true, nullable = false, name = "RID")
	private Long rID;

	@ManyToOne
	@JoinColumn(name = "KISIREF")
	private Kisi kisiRef;

	@Column(name = "SICILNO")
	private String sicilno;

	@Enumerated(EnumType.ORDINAL)
	@Column(name = "UYETIP")
	private UyeTip uyetip;

	@ManyToOne
	@JoinColumn(name = "BIRIMREF")
	private Birim birimRef;

	@Column(name = "ILETISIMSMS")
	private EvetHayir iletisimSms;

	@Column(name = "ILETISIMEMAIL")
	private EvetHayir iletisimEmail;

	@Column(name = "ILETISIMPOSTA")
	private EvetHayir iletisimPosta;

	@Temporal(TemporalType.DATE)
	@Column(name = "UYELIKTARIH")
	private java.util.Date uyeliktarih;

	@Temporal(TemporalType.DATE)
	@Column(name = "AYRILMATARIH")
	private java.util.Date ayrilmatarih;

	@Enumerated(EnumType.ORDINAL)
	@Column(name = "UYEDURUM")
	private UyeDurum uyedurum;

	@Enumerated(EnumType.ORDINAL)
	@Column(name = "KAYITDURUM")
	private UyeKayitDurum kayitdurum;

	@ManyToOne
	@JoinColumn(name = "ONAYLAYANREF")
	private Personel onaylayanRef;

	@Temporal(TemporalType.DATE)
	@Column(name = "ONAYTARIH")
	private java.util.Date onaytarih;

	@ManyToOne
	@JoinColumn(name = "OGRENCIUYEREF")
	private Uye ogrenciUyeRef;

	@Column(name = "OGRENCINO")
	private String ogrenciNo;

	@Column(name = "SINIF")
	private Integer sinif;

    @Temporal(TemporalType.DATE)
    @Column(name = "KART_TALEP_TARIHI")
    private java.util.Date kartTalepTarihi;

    @Temporal(TemporalType.DATE)
    @Column(name = "KART_TESLIM_TARIHI")
    private java.util.Date kartTeslimTarihi;

	@Column(name = "TESLIM_ADRESI")
	private String teslimAdresi;

	@Transient
	private boolean epostaIletisimi;

	@Transient
	private boolean telefonIletisimi;

	@Transient
	private boolean postaIletisimi;

	public boolean isEpostaIletisimi() {
		if (iletisimEmail==EvetHayir._EVET) {
			epostaIletisimi=true;
		} else {
			epostaIletisimi=false;
		}
		return epostaIletisimi;
	}

	public void setEpostaIletisimi(boolean epostaIletisimi) {
		if(epostaIletisimi){
			setIletisimEmail(EvetHayir._EVET);
		} else {
			setIletisimEmail(EvetHayir._HAYIR);
		}
		this.epostaIletisimi = epostaIletisimi;
	}

	public boolean isTelefonIletisimi() {
		if (iletisimSms==EvetHayir._EVET) {
			telefonIletisimi=true;
		} else {
			telefonIletisimi=false;
		}
		return telefonIletisimi;
	}

	public void setTelefonIletisimi(boolean telefonIletisimi) {
		if(telefonIletisimi){
			setIletisimSms(EvetHayir._EVET);
		} else {
			setIletisimSms(EvetHayir._HAYIR);
		}
		this.telefonIletisimi = telefonIletisimi;
	}

	public boolean isPostaIletisimi() {
		if (iletisimPosta==EvetHayir._EVET) {
			postaIletisimi=true;
		} else {
			postaIletisimi=false;
		}
		return postaIletisimi;
	}

	public void setPostaIletisimi(boolean postaIletisimi) {
		if(postaIletisimi){
			setIletisimPosta(EvetHayir._EVET);
		} else {
			setIletisimPosta(EvetHayir._HAYIR);
		}
		this.postaIletisimi = postaIletisimi;
	}

	public Uye() {
		super();
	}

	@Override
	public Long getRID() {
		return this.rID;
	}

	@Override
	public void setRID(Long rID) {
		this.rID = rID;
	}

	public Kisi getKisiRef() {
		return kisiRef;
	}

	public void setKisiRef(Kisi kisiRef) {
		this.kisiRef = kisiRef;
	}

	public String getSicilno() {
		return this.sicilno;
	}

	public void setSicilno(String sicilno) {
		this.sicilno = sicilno;
	}

	public UyeTip getUyetip() {
		return this.uyetip;
	}

	public void setUyetip(UyeTip uyetip) {
		this.uyetip = uyetip;
	}

	public Birim getBirimRef() {
		return birimRef;
	}

	public void setBirimRef(Birim birimRef) {
		this.birimRef = birimRef;
	}

	public EvetHayir getIletisimSms() {
		return iletisimSms;
	}

	public void setIletisimSms(EvetHayir iletisimSms) {
		this.iletisimSms = iletisimSms;
	}

	public EvetHayir getIletisimEmail() {
		return iletisimEmail;
	}

	public void setIletisimEmail(EvetHayir iletisimEmail) {
		this.iletisimEmail = iletisimEmail;
	}

	public EvetHayir getIletisimPosta() {
		return iletisimPosta;
	}

	public void setIletisimPosta(EvetHayir iletisimPosta) {
		this.iletisimPosta = iletisimPosta;
	}

	public java.util.Date getUyeliktarih() {
		return uyeliktarih;
	}

	public void setUyeliktarih(java.util.Date uyeliktarih) {
		this.uyeliktarih = uyeliktarih;
	}

	public java.util.Date getAyrilmatarih() {
		return ayrilmatarih;
	}

	public void setAyrilmatarih(java.util.Date ayrilmatarih) {
		this.ayrilmatarih = ayrilmatarih;
	}

	public UyeDurum getUyedurum() {
		return this.uyedurum;
	}

	public void setUyedurum(UyeDurum uyedurum) {
		this.uyedurum = uyedurum;
	}

	public UyeKayitDurum getKayitdurum() {
		return this.kayitdurum;
	}

	public void setKayitdurum(UyeKayitDurum kayitdurum) {
		this.kayitdurum = kayitdurum;
	}

	public Personel getOnaylayanRef() {
		return onaylayanRef;
	}

	public void setOnaylayanRef(Personel onaylayanRef) {
		this.onaylayanRef = onaylayanRef;
	}

	public java.util.Date getOnaytarih() {
		return onaytarih;
	}

	public void setOnaytarih(java.util.Date onaytarih) {
		this.onaytarih = onaytarih;
	}

	public Uye getOgrenciUyeRef() {
		return ogrenciUyeRef;
	}

	public void setOgrenciUyeRef(Uye ogrenciUyeRef) {
		this.ogrenciUyeRef = ogrenciUyeRef;
	}

	public String getOgrenciNo() {
		return ogrenciNo;
	}

	public void setOgrenciNo(String ogrenciNo) {
		this.ogrenciNo = ogrenciNo;
	}

	public Integer getSinif() {
		return sinif;
	}

	public void setSinif(Integer sinif) {
		this.sinif = sinif;
	}

    public Date getKartTalepTarihi() {
        return kartTalepTarihi;
    }

    public void setKartTalepTarihi(Date kartTalepTarihi) {
        this.kartTalepTarihi = kartTalepTarihi;
    }

	@Transient
	public BigDecimal getUyeAidatBorc() {
		return ManagedBeanLocator.locateSessionController().getUyeAidatBorc(getRID());
	}

	@Transient
	public Adres getVarsayilanAdres() {
		try {
			if(getDBOperator().recordCount(Adres.class.getSimpleName(), "o.kisiRef.rID=" + getKisiRef().getRID()) > 0){
				return (Adres) getDBOperator().load(Adres.class.getSimpleName(), "o.kisiRef.rID=" + getKisiRef().getRID(), "o.varsayilan ASC, o.beyanTarihi DESC").get(0);
			} else {
				return null;
			}
		} catch(Exception e){
			return null;
		}
	}

	@Transient
	public Adres getEvAdres() {
		try {
			if(getDBOperator().recordCount(Adres.class.getSimpleName(), "o.kisiRef.rID=" + getKisiRef().getRID() + " AND o.adresturu=" + AdresTuru._EVADRESI.getCode()) > 0){
				return (Adres) getDBOperator().load(Adres.class.getSimpleName(), "o.kisiRef.rID=" + getKisiRef().getRID() +
						" AND o.adresturu=" + AdresTuru._EVADRESI.getCode() , "o.varsayilan ASC, o.beyanTarihi DESC").get(0);
			} else {
				return null;
			}
		} catch(Exception e){
			return null;
		}
	}


	@Transient
	public Kurum getKurum() {
		try {
			if(getDBOperator().recordCount(KurumKisi.class.getSimpleName(), "o.kisiRef.rID=" + getKisiRef().getRID() + " AND o.uyekurumDurum=" +UyekurumDurum._CALISIYOR.getCode() + " AND o.varsayilan=" + EvetHayir._EVET.getCode()) > 0){
				KurumKisi kurumkisi =(KurumKisi) getDBOperator().load(KurumKisi.class.getSimpleName(), "o.kisiRef.rID=" + getKisiRef().getRID()+" AND o.uyekurumDurum="
						+UyekurumDurum._CALISIYOR.getCode()+ " AND o.varsayilan=" + EvetHayir._EVET.getCode(),"").get(0);
				return kurumkisi.getKurumRef();
			} else {
				return null;
			}
		} catch(Exception e){
			return null;
		}
	}

	public String getOnaylanmamisSicilNo() {
		if (getSicilno()!=null && getKayitdurum().getCode()== UyeKayitDurum._ONAYLANMIS.getCode()){
			return "<span style=\"color:black;\">" + getSicilno() + "</span>";
		}else if (getSicilno()!=null && getKayitdurum().getCode()!= UyeKayitDurum._ONAYLANMIS.getCode()) {
			return "<span style=\"color:red;\">" + getSicilno()  + "</span>";
		}else {
			return null;
		}
	}

	public String getOnaylanmamisUye() {
		if (getKisiRef()!=null){
			if (getSicilno()!=null && getKayitdurum().getCode()== UyeKayitDurum._ONAYLANMIS.getCode()){
				return "<span style=\"color:black;\">" + getKisiRef().getUIStringShort() + "</span>";
			}else if (getSicilno()==null && getKayitdurum().getCode()!= UyeKayitDurum._ONAYLANMIS.getCode()) {
				return "<span style=\"color:red;\">" + getKisiRef().getUIStringShort() + "</span>";
			} else if (getSicilno()!=null && getKayitdurum().getCode()!= UyeKayitDurum._ONAYLANMIS.getCode()) {
				return "<span style=\"color:red;\">" + getKisiRef().getUIStringShort() + "</span>";
			}
		}
		return getKisiRef().getUIString();


	}

	@Transient
	public KurumKisi getUyekurum() {
		try {
			if(getDBOperator().recordCount(KurumKisi.class.getSimpleName(), "o.kisiRef.rID=" + getKisiRef().getRID()) > 0){
				KurumKisi uyeKurum =(KurumKisi) getDBOperator().load(KurumKisi.class.getSimpleName(), "o.kisiRef.rID=" + getKisiRef().getRID(),"").get(0);
				return uyeKurum;
			}
		} catch(Exception e){

		}
		return null;

	}

	@Transient
	public Kisiogrenim getUyeogrenim() {
		try {

Toys/JavaSource/tr/com/arf/toys/db/model/uye/Uyeaidat.java
package tr.com.arf.toys.db.model.uye;

import java.math.BigDecimal;
import java.math.MathContext;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import tr.com.arf.framework.utility.tool.BigDecimalUtil;
import tr.com.arf.framework.utility.tool.KeyUtil;
import tr.com.arf.toys.db.enumerated.uye.UyeAidatDurum;
import tr.com.arf.toys.db.model.base.ToysBaseEntity;

@Entity
@Table(name = "UYEAIDAT")
public class Uyeaidat extends ToysBaseEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(updatable = false, unique = true, nullable = false, name = "RID")
	private Long rID;

	@ManyToOne
	@JoinColumn(name = "UYEREF")
	private Uye uyeRef;

	@Column(name = "YIL")
	private int yil;

	@Column(name = "AY")
	private int ay;

	@Column(name = "MIKTAR")
	private BigDecimal miktar;

	@Column(name = "ODENEN")
	private BigDecimal odenen;

	@Enumerated(EnumType.ORDINAL)
	@Column(name = "UYEAIDATDURUM")
	private UyeAidatDurum uyeaidatdurum;

	@ManyToOne
	@JoinColumn(name = "UYEMUAFIYETREF")
	private Uyemuafiyet uyemuafiyetRef;

	public Uyeaidat() {
		super();
	}

	@Override
	public Long getRID() {
		return this.rID;
	}

	@Override
	public void setRID(Long rID) {
		this.rID = rID;
	}

	public Uye getUyeRef() {
		return uyeRef;
	}

	public void setUyeRef(Uye uyeRef) {
		this.uyeRef = uyeRef;
	}

	public int getYil() {
		return this.yil;
	}

	public void setYil(int yil) {
		this.yil = yil;
	}

	public int getAy() {
		return this.ay;
	}

	public void setAy(int ay) {
		this.ay = ay;
	}

	public UyeAidatDurum getUyeaidatdurum() {
		return this.uyeaidatdurum;
	}

	public void setUyeaidatdurum(UyeAidatDurum uyeaidatdurum) {
		this.uyeaidatdurum = uyeaidatdurum;
	}

	public Uyemuafiyet getUyemuafiyetRef() {
		return uyemuafiyetRef;
	}

	public void setUyemuafiyetRef(Uyemuafiyet uyemuafiyetRef) {
		this.uyemuafiyetRef = uyemuafiyetRef;
	}

	public BigDecimal getMiktar() {
		return BigDecimalUtil.changeToCurrency(this.miktar);
	}

	public void setMiktar(BigDecimal miktar) {
		this.miktar = BigDecimalUtil.changeToCurrency(miktar);
	}

	public BigDecimal getOdenen() {
		return BigDecimalUtil.changeToCurrency(this.odenen);
	}

	public void setOdenen(BigDecimal odenen) {
		this.odenen = BigDecimalUtil.changeToCurrency(odenen);
		uyeAidatDurumGuncelle();
	}

	// @Transient
	// public int getAidatYili() {
	// try {
	// if(getDBOperator().recordCount() > 0){
	// return (Adres) getDBOperator().load(Adres.class.getSimpleName(), "o.kisiRef.rID=" + getKisiRef().getRID() +
	// " AND o.adresturu=" + AdresTuru._EVADRESI.getCode() , "o.varsayilan ASC, o.beyanTarihi DESC").get(0);
	// } else {
	// return null;
	// }
	// } catch(Exception e){
	// return null;
	// }
	// }

	public BigDecimal getKalan() {
		if (getUyemuafiyetRef() == null) {
			MathContext mc = new MathContext(0);
			mc = MathContext.DECIMAL32;
			return BigDecimalUtil.changeToCurrency(this.miktar.subtract(this.odenen, mc));
		} else {
			return BigDecimalUtil.changeToCurrency(new BigDecimal(0L));
		}
	}

	public void uyeAidatDurumGuncelle() {
		if (getUyemuafiyetRef() != null) {
			setUyeaidatdurum(UyeAidatDurum._MUAF);
		} else if (getKalan().longValue() < 0) {
			setUyeaidatdurum(UyeAidatDurum._ALACAKLI);
		} else if (getKalan().longValue() == 0) {
			setUyeaidatdurum(UyeAidatDurum._ODENMIS);
		} else if (getKalan().longValue() > 0) {
			setUyeaidatdurum(UyeAidatDurum._BORCLU);
		}
	}

	@Override
	public String toString() {
		return "tr.com.arf.toys.db.model.uye.Uyeaidat[id=" + this.getRID() + "]";
	}

	@Override
	public String getUIString() {
		return getYil() + "-" + getAy() + " Kalan :" + getKalan();
	}

	@Override
	public void initValues(boolean defaultValues) {
		if (defaultValues) {
			// TODO Initialize with default values
		} else {
			this.rID = null;
			this.uyeRef = null;
			this.yil = 0;
			this.ay = 0;
			this.miktar = null;
			this.odenen = null;
			this.uyeaidatdurum = UyeAidatDurum._NULL;
			this.uyemuafiyetRef = null;
		}
	}

	@Override
	public String getValue() {
		StringBuilder value = new StringBuilder("");
		if (getUyeRef() != null) {
			value.append(KeyUtil.getLabelValue("uyeaidat.uyeRef") + " : " + getUyeRef().getUIString() + "<br />");
		}
		if (getYil() != 0) {
			value.append(KeyUtil.getLabelValue("uyeaidat.yil") + " : " + getYil() + "<br />");
		}
		if (getAy() != 0) {
			value.append(KeyUtil.getLabelValue("uyeaidat.ay") + " : " + getAy() + "<br />");
		}
		if (getMiktar() != null) {
			value.append(KeyUtil.getLabelValue("uyeaidat.miktar") + " : " + getMiktar() + "<br />");
		}
		if (getOdenen() != null) {
			value.append(KeyUtil.getLabelValue("uyeaidat.odenen") + " : " + getOdenen() + "<br />");
		}
		if (getUyeaidatdurum() != null) {
			value.append(KeyUtil.getLabelValue("uyeaidat.uyeaidatdurum") + " : " + getUyeaidatdurum() + "");
		}
		if (getUyemuafiyetRef() != null) {
			value.append(KeyUtil.getLabelValue("uyeaidat.uyemuafiyetRef") + " : " + getUyemuafiyetRef().getUIString() + "");
		}
		return value.toString();
	}

}

Toys/JavaSource/tr/com/arf/toys/db/model/uye/Uyeform.java
package tr.com.arf.toys.db.model.uye;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import tr.com.arf.framework.db.model._base.BaseEntity;
import tr.com.arf.framework.utility.tool.KeyUtil;
import tr.com.arf.toys.db.enumerated.uye.Formturu;

@Entity
@Table(name = "UYEFORM")
public class Uyeform extends BaseEntity {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(updatable = false, unique = true, nullable = false, name = "RID")
	private Long rID;

	@ManyToOne
	@JoinColumn(name = "UYEREF")
	private Uye uyeRef;

	@Enumerated(EnumType.ORDINAL)
	@Column(name = "FORMTURU")
	private Formturu formturu;

	@Column(name = "PATH")
	private String path;

	public Uyeform() {
		super();
	}

	@Override
	public Long getRID() {
		return this.rID;
	}

	@Override
	public void setRID(Long rID) {
		this.rID = rID;
	}

	public Uye getUyeRef() {
		return uyeRef;
	}

	public void setUyeRef(Uye uyeRef) {
		this.uyeRef = uyeRef;
	}

	public Formturu getFormturu() {
		return this.formturu;
	}

	public void setFormturu(Formturu formturu) {
		this.formturu = formturu;
	}

	@Override
	public String getPath() {
		return this.path;
	}

	@Override
	public void setPath(String path) {
		this.path = path;
	}

	@Override
	public String toString() {
		return getUIString();
	}

	@Override
	public String getUIString() {
		return getPath() + "";
	}

	@Override
	public void initValues(boolean defaultValues) {
		this.rID = null;
		this.uyeRef = null;
		this.formturu = Formturu._NULL;
		this.path = "";
	}

	@Override
	public String getValue() {
		StringBuilder value = new StringBuilder("Veri : <br />");
		if (getUyeRef() != null) {
			value.append(KeyUtil.getLabelValue("uyeform.uyeRef") + " : " + getUyeRef().getUIString() + "<br />");
		}
		if (getFormturu() != null) {
			value.append(KeyUtil.getLabelValue("uyeform.formturu") + " : " + getFormturu().getLabel() + "<br />");
		}
		if (getPath() != null) {
			value.append(KeyUtil.getLabelValue("uyeform.path") + " : " + getPath() + "");
		}
		return value.toString();
	}

}

Toys/WebContent/_page/form/uye/uyeDetay/uyeaidat.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:arf="http://java.sun.com/jsf/composite/arfComposite" xmlns:arftags="http://arf.com/column" template="/_page/_main/main.xhtml">

	<ui:define name="content">
		<h:body>
			<h:form id="uyeaidatForm" prependId="false">

				<arf:masterPanel controllerClassName="#{uyeaidatController}" masterLabel="#{label['uye.list']}" modelName="uyeaidat" />

				<ui:include src="/_page/form/uye/uyeDetay/uyeaidat_Edit.xhtml" />

				<p:fieldset legend="#{label['uyeaidat.list']}" styleClass="pageFieldSet" id="uyeaidatListPanel">
					<h:panelGrid columns="10" border="0" style="text-align:center" cellspacing="0" cellpadding="0">
						<p:commandButton id="uyemuafiyetCommand" process="@this" icon="child" action="#{uyeaidatController.uyemuafiyet}"
							rendered="#{uyeaidatController.listRenderedFor('Uyemuafiyet')}"
							disabled="#{uyeaidatController.uyeaidat.RID == null or uyeaidatController.uyeaidat.uyemuafiyetRef == null}" value="#{label['command.uyemuafiyet']}"
							styleClass="arfCommandButton" />
						<p:commandButton id="uyeodemeCommand" process="@this" icon="child" action="#{uyeaidatController.uyeodeme}" rendered="#{uyeaidatController.listRenderedFor('Uyeodeme')}"
							disabled="#{uyeaidatController.uyeaidat.RID == null}" value="#{label['command.uyeodeme']}" styleClass="arfCommandButton" />

					</h:panelGrid>
					<p:blockUI block="uyeaidatTable" trigger="uyeaidatTable">
						<h:outputText value="#{label['common.loading']}" />
						<br />
						<h:graphicImage library="_image" name="ajax-loader.gif" />
					</p:blockUI>
					<p:dataTable emptyMessage="#{label['primefaces.noRecordFound']}" style="margin-top:10px" id="uyeaidatTable" value="#{uyeaidatController.list}" var="uyeaidatRow" binding="#{uyeaidatController.table}" rowIndexVar="rowIndex"
						selectionMode="single" selection="#{uyeaidatController.entity}" filteredValue="#{uyeaidatController.filteredList}" widgetVar="filterTable" rowKey="#{uyeaidatRow.RID}"
						resizableColumns="false">

						<p:ajax event="rowSelect" listener="#{uyeaidatController.tableRowSelect}" update=":uyeaidatForm" />
						<p:ajax event="rowUnselect" listener="#{uyeaidatController.tableRowCancelSelection}" update=":uyeaidatForm" />

						<arftags:column val="#{uyeaidatRow.yil}" header="#{label['uyeaidat.yil']}" width="6" />
						<arftags:column val="#{uyeaidatRow.ay}" header="#{label['uyeaidat.ay']}" width="6" />
						<arftags:filteredNumericColumn filterMatchMode="contains" val="#{uyeaidatRow.miktar}" header="#{label['uyeaidat.miktar']}" width="10" />
						<arftags:filteredNumericColumn filterMatchMode="contains" val="#{uyeaidatRow.odenen}" header="#{label['uyeaidat.odenen']}" width="10" />
						<arftags:filteredNumericColumn filterMatchMode="contains" val="#{uyeaidatRow.kalan}" header="#{label['uyeaidat.kalan']}" width="10" />
						<arftags:column val="#{uyeaidatRow.uyeaidatdurum.label}" header="#{label['uyeaidat.uyeaidatdurum']}" width="20" />

					</p:dataTable>

					<arf:pagingWithBlockUI controllerClassName="#{uyeaidatController}" formName="uyeaidatForm" listPanelName="uyeaidatListPanel" pagingOption="false"
						tableName="uyeaidatTable" addExport="true" addOption="true" updateOption="true" deleteOption="true" addSubRecordOption="false" />
				</p:fieldset>
			</h:form>
		</h:body>
	</ui:define>
</ui:composition>

Toys/WebContent/_page/form/uye/uyeDetay/uyeuzmanlik_Edit.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:arf="http://java.sun.com/jsf/composite/arfComposite" xmlns:arftags="http://arf.com/column">

	<p:fieldset id="uyeuzmanlikEditPanel" toggleable="false" styleClass="pageFieldSet" legend="#{label['uyeuzmanlik.edit']}" rendered="#{uyeuzmanlikController.editPanelRendered}">
		<h:panelGrid columns="3" columnClasses="otuzUcYuzde, otuzUcYuzde, otuzUcYuzde" styleClass="arfEditGrid">


			<arf:dropdown label="#{label['uyeuzmanlik.uzmanliktipRef']}" listSource="#{uyeuzmanlikController.selectItemListFor('Uzmanliktip')}" requiredCond="true"
				compId="uzmanliktipRef" value="#{uyeuzmanlikController.uyeuzmanlik.uzmanliktipRef}" converterId="#{'uzmanliktipConverter'}" id="uzmanliktipRefDropDown" />

			<arf:textinput label="#{label['uyeuzmanlik.aciklama']}" value="#{uyeuzmanlikController.uyeuzmanlik.aciklama}" compId="aciklama" requiredCond="false" id="aciklamaInputText"
				maxLength="200" />

		</h:panelGrid>

		<arf:editPanelBottomWithBlockUI controllerClassName="#{uyeuzmanlikController}" formName="uyeuzmanlikForm" listPanelName="uyeuzmanlikListPanel"
			editPanelName="uyeuzmanlikEditPanel" modelName="Uyeuzmanlik" />
	</p:fieldset>

</ui:composition>